//
//  RealmKey.swift
//  Live3s
//
//  Created by ALWAYSWANNAFLY on 6/1/16.
//  Copyright © 2016 com.phucnguyen. All rights reserved.
//

struct LanguageKey {
    static let id = "id"
    static let oneXtwo = "oneXtwo"
    static let alert = "alert"
    static let all = "all"
    static let away = "away"
    static let cancel = "cancel"
    static let chap = "chap"
    static let club = "club"
    static let common = "common"
    static let connect_grant = "connect_grant"
    static let data_updating = "data_updating"
    static let detail = "detail"
    static let dismiss = "dismiss"
    static let extra_subject = "extra_subject"
    static let extra_text = "extra_text"
    static let face_to_face = "face_to_face"
    static let favorite_my_competitions = "favorite_my_competitions"
    static let favorite_my_score = "favorite_my_score"
    static let first_goals = "first_goals"
    static let fixtures = "fixtures"
    static let form = "form"
    static let formation_off = "formation_off"
    static let formation_sub = "formation_sub"
    static let ft = "ft"
    static let goal = "goal"
    static let home = "home"
    static let input_search_here = "input_search_here"
    static let label_total_draw = "label_total_draw"
    static let label_total_lose = "label_total_lose"
    static let label_total_match = "label_total_match"
    static let label_total_point = "label_total_point"
    static let label_total_win = "label_total_win"
    static let languages = "languages"
    static let last_five_match = "last_five_match"
    static let leagues = "leagues"
    static let line_up = "line_up"
    static let load_data_fail = "load_data_fail"
    static let loading = "loading"
    static let lost_connect = "lost_connect"
    static let match = "match"
    static let match_cast = "match_cast"
    static let match_finish = "match_finish"
    static let match_not_start = "match_not_start"
    static let match_stats = "match_stats"
    static let no_data = "no_data"
    static let normal = "normal"
    static let notstart = "notstart"
    static let ok = "ok"
    static let penalty_goals = "penalty_goals"
    static let player = "player"
    static let postpone = "postpone"
    static let rank = "rank"
    static let reconnect = "reconnect"
    static let result = "result"
    static let round = "round"
    static let season = "season"
    static let table = "table"
    static let taixiu = "taixiu"
    static let team = "team"
    static let times = "times"
    static let tip_free = "tip_free"
    static let tip_last_match = "tip_last_match"
    static let tip_pick = "tip_pick"
    static let tip_tip = "tip_tip"
    static let tip_vip = "tip_vip"
    static let today = "today"
    static let top_scorers = "top_scorers"
    static let tv_guide = "tv_guide"
    static let update_app_title = "update_app_title"
    static let view_more_at_web = "view_more_at_web"
    static let vip = "vip"
    static let label_goal_for = "label_goal_for"
    static let label_goal_against = "label_goal_for"
}
